buttonInfoAcount =                       "xpath=//span[@class='l-header__bottom-item-title has-arrow']"
acountInfo =                             "xpath=//a[@class='account__sidebar__nav__list__link__item sel-menu-info']"
pathLocatorInfoConta =                   "xpath=//h2[text()='Informações da conta']"
buttonPassword =                         "xpath=//p[@class='accountStep3__row__link__text']"
confirmPasswordPath =                    "xpath=(//input[@class='checkout__forms__passForm__input'])[2]"
newPasswordPath =                        "xpath=(//input[@class='checkout__forms__passForm__input'])[3]"
confirmNewPasswordPath =                 "xpath=(//input[@class='checkout__forms__passForm__input'])[4]"
buttonConfirmPasswordChange =            "xpath=(//button[@class='accountPopup__btn btn-primary'])[2]"
pathMsgPasswordSuccess =                 "xpath=//div[text()='Senha editada com sucesso']"

pathName =                               "xpath=//input[@class='checkout__forms__nameForm__input qa-accountInput__firstNameInput']"
lastNamePath =                           "xpath=//input[@class='checkout__forms__lastNameForm__input qa-accountInput__lastNameInput']"
buttonSalvar =                           "xpath=//*[@id='content']/div[2]/main/div[2]/div[1]/div[2]/form/button"
msgSucess =                              "Alterado com sucesso"
msgSuccessPath =                         "xpath=//div[text()='Alterado com sucesso']"
saudacaoSra =                            "xpath=//*[@id='uniform-frau-input']"
saudacaoSr =                             "xpath=//*[@id='uniform-herr-input']/span"
msgError =                               "Campo obrigatório"
msgError_path =                          "//div[text()='Campo obrigatório']"
pathMsgPasswordErrorAtual =              "xpath=//div[text()='Senha atual não pode ser vazio.']"
pathMsgPasswordErrorNova =               "xpath=//div[text()='Nova senha não pode ser vazio.']"
pathMsgPasswordErrorConfirme =           "xpath=//div[text()='Confirme a nova senha não pode ser vazio.']"
wrongPasswordMsg =                       "//div[text()='Senha incorreta.']"
moreThan50CaracteresMsg =                "//div[text()='Máximo 50 caracteres']"
lessThan06CaracteresMsg =                "//div[text()='Min 6 caracteres']"
msgSenhasNaoIguais =                     "//div[text()='As senhas não estão iguais']"
empty =                                  ""
spaces =                                 "    "