productName = "xpath=(.//*[@class='blockProduct__name blockProduct__headingTagProduct  qaBlockProduct__name'])"
category = "xpath=(.//span[@class='l-header__nav-tag'])"
wishlistIconInactive = "xpath=(.//*[@class='blockWishlistHeart__icon blockWishlistHeart__icon_pasive '])"
imageProduct ="xpath=(.//img[@class='blockListProduct__image'])"
productSize = "xpath=(.//*[@class='blockListProduct__size'])"
productPrice = "xpath=(.//*[@class='blockListProduct__price'])"
productSize = "xpath=(.//*[@class='blockListProduct__size'])"
buttonDeleteFromWishlist = "xpath=.//*[@class='blockListProduct__delete qaBlockListProduct__delete']"
wishlistNoProductsInfo = "xpath=.//*[@class='wishlistNoProducts__info']"
selectWishlist = "xpath=.//*[@class='blockAddToWishlistOverlay__headerText']"
addToWishlistButton = "xpath=.//*[@class='blockAddToWishlistOverlay__confirm qaBlockAddToWishlistOverlay__confirm btn-primary']"
closeAddWishlist = "xpath=.//*[@class='blockAddToWishlistOverlay__close qaBlockAddToWishlistOverlay__close']"
wishlistButton = "xpath=.//*[@class='l-header__bottom-item-icon l-header__bottom-item-icon--wishlist']"
addWishlistButton = "xpath=.//*[@class='blockWishlistButton btn-default qa-addToWishlistBtn jsWishlistButton blockWishlistButton--active']"
newWishlist = "xpath=.//*[@class='blockAddToWishlistOverlay__addNewList qaBlockAddToWishlistOverlay__addNewList']"
newWishlistName = "xpath=.//*[@class='blockAddToWishlistOverlay__input']"
addListButton = "xpath=.//*[@class='blockWishlistNavigation__addListButton qaBlockWishlistNavigation__addListButton']"
inputAddListButtonName = "xpath=.//*[@class='blockCreateListOverlay__input']"
addButton = "xpath=.//*[@class='btn-primary blockCreateListOverlay__confirm qaBlockCreateListOverlay__confirm']"
loginNow= "xpath=.//*[@class='blockRegisterPanel__switchButton qa-blockRegisterPanel__switchButton']"
cookiePolicyOverlay= "xpath=.//*[@class='cookiePolicyOverlay__close']"
identifierTextFieldWishlist = "name=LoginForm[email]"
passwordTextFieldWishlist = "name=LoginForm[password]"
buttonLoginWishlist = "xpath=.//*[@class='newLogin blockLoginForm__submit qa-blockLoginForm__submit is-react']"
changeWishlist = "xpath=.//*[@class='blockActionMenu__icon blockActionMenu__icon_sort']"
myWishlist = "xpath=.//*[@class='blockAddToWishlistOverlay__list qaBlockAddToWishlistOverlay__list0']"
productNameWishlist = "xpath=.//*[@class='blockListProduct__name']"
listName = "xpath=.//*[@class='blockWishlistNavigation__listName']"
editWishlist = "xpath=.//*[@class='wishlist__lists__action__addList qaWishlist__lists__action__addList btn-default']"
inputListName = "xpath=.//*[@class='blockEditListOverlay__input']"
renameList = "xpath=.//*[@class='blockEditListOverlay__confirm qaBlockEditListOverlay__confirm btn-primary']"
deleteList = "xpath=.//*[@class='blockEditListOverlay__delete qaBlockEditListOverlay__delete btn-default']"
confirmButton = "xpath=.//*[@class='blockConfirmOverlay__confirm jsBlockConfirmOverlay__confirm qaBlockConfirmOverlay__confirm']"

