homeTitle =                         "WestwingNow | Loja de Decoração, Mesa Posta e Tapetes"
buttonAddCart =                     "xpath=//*[@id='buttonText']"
buttonCart =                        "xpath=//span[@class='l-header__bottom-item-icon l-header__bottom-item-icon--cart']"
buttonCartComprar =                 "xpath=//*[@id='cart']/div[3]/div[1]/button/p"
checkoutButtonPix =                 "xpath=//*[@id='uniform-pix']/span"
checkoutButtonContinuar =           "xpath=//span[text()='Continuar']"
textConfirmarPedido =               "Confirmar pedido"
checkoutButtonCompreAgora =         "xpath=//*[@id='js-formFinish-bottom']/div[2]/button/span"
textPurchaseSuccess =               "                    Ler o QR Code                "

homeButtonMoveis =                  "xpath=//*[@id='page']/nav/div/ul/li[1]/a/span"
moveisTitle =                       "Móveis para toda casa até 10x s/juros* | WestwingNow"
produtoMoveis =                     "xpath=//*[@id='DEQ20MOV64220-7582-image-1']"

homeButtonCamaeBanho =              "xpath=//*[@id='page']/nav/div/ul/li[2]/a/span"
camaeBanhoTitle =                   "Cama e banho: Melhores produtos para o seu lar | WestwingNow"
produtoCamaeBanho =                 "xpath=//*[@id='DEQ20LAV54547-15390-image-1']"

homeButtonTapeteseCortinas =        "xpath=//*[@id='page']/nav/div/ul/li[3]/a/span"
tapeteseCortinasTitle =             "Tapetes para Sala, Quarto e Banheiro | WestwingNow"
produtoTapeteseCortinas =           "xpath=//*[@id='DEQ21WES78211-43526-image-1']"

homeButtonDecoracaoeIluminacao =    "xpath=//*[@id='page']/nav/div/ul/li[4]/a/span"
decoracaoeIluminacaoTitle =         "Decoração: Design Exclusivo e Alta Qualidade | WestwingNow"
produtoDecoracaoeIluminacao =       "xpath=//*[@id='DEQ21MAD67687-31013-image-1']"

homeButtonMesaPosta =               "xpath=//*[@id='page']/nav/div/ul/li[5]/a/span"
mesaPostaTitle =                    "Mesa posta é no WestwingNow"
produtoMesaPosta =                  "xpath=//*[@id='DEQ20WES08325-23802-image-1']"

homeButtonCozinha =                 "xpath=//*[@id='page']/nav/div/ul/li[6]/a"
cozinhaTitle =                      "Cozinha"
produtoCozinha =                    "xpath=//*[@id='DEQ21KIT59673-38516-image-1']"

homeButtonInfantil =                "xpath=//*[@id='page']/nav/div/ul/li[7]/a/span"
infantilTitle =                     "Infantil | WestwingNow"
produtoInfantil =                   "xpath=//*[@id='DEQ21VIQ50903-31427-image-1']"

homeButtonPets =                    "xpath=//*[@id='page']/nav/div/ul/li[8]/a/span"
petsTitle =                         "Pets | WestwingNow"
produtoPets =                       "xpath=//*[@id='DEQ21WOO22964-55026-image-1']"

inputProduto =                      "xpath=//*[@id='searchInput']"

primeiroProduto =                   "(//a[@class='jsProductListItemLink qaBlockProduct__link gtmBlockProduct__link blockProduct__link  '])[1]"
buscaTitle =                        "Resultados de busca | WestwingNow "

checkoutEndereco =                  "xpath=//*[@id='content']/div/div[1]/div/ul/li[1]/a"
checkboxAlterarEndereco =           "name=shippingAddressDifferent"
ponteiroEndCobranca=                "xpath=//*[@id='js-formAddress']/div[2]/div/div[3]/div[1]/h2"
saudacaoCampo=                      "xpath=//*[@id='js-shippingForm']/div[2]/div/div/div[1]/div"
saudacaoSr =                        "xpath=//*[@id='uniform-shipping-herr-input']/span"
sr =                                "Sr."
saudacaoSra =                       "xpath=//*[@id='uniform-shipping-frau-input']/span"
sra =                               "Sra."
pathprimeiroNome =                  "xpath=//*[@id='shipping-name-input']"
primeiroNomeSr =                    "Teste 1" 
primeiroNomeSra =                   "Teste 2" 
pathsobreNome =                     "xpath=//*[@id='shipping-lastName-input']"
sobreNomeSr =                       "endereco 1"
sobreNomeSra =                      "endereco2"
pathcep =                           "id=shipping-code-input"
cepSr =                             "07950250"
cepSra =                            "07929000"
cepBuy =                            "id=billing-code-input"
pathcidade =                        "xpath=//*[@id='shipping-city-input']"
cidadeSr =                          "Francisco Morato"
cidadeSra =                         "Francisco Morato"
pathendereco =                      "xpath=//*[@id='shipping-street']"
enderecoSr =                        "Luiz Vicentina Natalicio "
enderecoSra =                       "Seringueiras"
pathnumero =                        "xpath=//*[@id='shipping-street_number-input']"
numeroSr =                          "999"
numeroSra =                         "555"
pathbairro =                        "xpath=//*[@id='shipping-neighborhood-input']"
bairroSr =                          "Antomar"
BairroSra =                         "Jardim"
pathtelefone =                      "xpath=//*[@id='shipping-phone-input']"
telefoneSr =                        "11995588774"
telefoneSra =                       "11225566998"
estado =                            "xpath=//*[@id='s2id_shipping-region-input']/a/span[2]"
selecionarEstado =                  "xpath=//*[@id='select2-result-label-28']"
enderecoContinuar =                 "xpath=//*[@id='js-formAddress']/div[3]/div/button"
add_to_cart_confirm =               "//a[@class='l-header__bottom-cart-button btn-primary']"
campanha1 =                         "(//a[@class='homeSlider__item item js-gtm-track-click slick-slide'][1])"
validaProductAtCart =               "//a[@class='l-header__bottom-cart-button btn-primary']"
