buttonRegister = "class=l-header__bottom-item-subline"
firstNameTextField = "id=CheckoutShortRegistrationForm_first_name"
lastNameTextField = "id=CheckoutShortRegistrationForm_last_name"
emailTextField = "id=CheckoutShortRegistrationForm_email"
passwordTextField = "id=CheckoutShortRegistrationForm_password"
acceptedTerms = "id=CheckoutShortRegistrationForm_is_tc_accepted"
buttonRegisterForFree = "name=register"
firstNameTextFieldError = "id=CheckoutShortRegistrationForm_first_name-error"
lastNameTextFieldError = "id=CheckoutShortRegistrationForm_last_name-error"
emailTextFieldError="id=CheckoutShortRegistrationForm_email-error"
passwordTextFieldError = "id=CheckoutShortRegistrationForm_password-error"
notAcceptTermsError = "css=.step1 .checkout__main .checkout__forms__right .checkout__forms__formBox .checkout__forms__form .checkout__forms__info1Form .s-error"
